<a href="https://colab.research.google.com/github/mahi0097/ML_Learning/blob/main/Logistic_Regression_multi_class.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt



In [2]:
veg_table_file = pd.read_csv("avocado_ripeness_dataset.csv")
veg_table_file.head()

firmness  hue  saturation  brightness color_category  sound_db  weight_g  \
0      14.5   19          40          26          black        34       175   
1      71.7   53          69          75          green        69       206   
2      88.5   60          94          46     dark green        79       220   
3      93.8  105          87          41     dark green        75       299   
4      42.5  303          58          32         purple        63       200   

   size_cm3         ripeness  
0       261             ripe  
1       185  pre-conditioned  
2       143             hard  
3       140             hard  
4       227         breaking

Finding Null Values

In [3]:
veg_table_file.isnull().sum()

firmness          0
hue               0
saturation        0
brightness        0
color_category    0
sound_db          0
weight_g          0
size_cm3          0
ripeness          0
dtype: int64

Encode Target Column
hard → 0  
breaking → 1  
ripe → 2  
pre-conditioned → 3


In [4]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
veg_table_file['ripness_encoder'] = encoder.fit_transform(veg_table_file['ripeness'])
print(veg_table_file[['ripeness', 'ripness_encoder']])

            ripeness  ripness_encoder
0               ripe                4
1    pre-conditioned                3
2               hard                2
3               hard                2
4           breaking                0
..               ...              ...
245             hard                2
246        firm-ripe                1
247             ripe                4
248  pre-conditioned                3
249             ripe                4

[250 rows x 2 columns]


Define Features (X) and Target (y)


In [5]:
x = veg_table_file.drop('ripness_encoder' ,axis= 1)
y = veg_table_file['ripness_encoder']

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(x,y,test_size = 0.2, random_state = 42)

In [7]:
from sklearn.linear_model import LogisticRegression
model  = LogisticRegression()



In [8]:
X_train = pd.get_dummies(X_train, columns=['color_category'], drop_first=True)
X_test = pd.get_dummies(X_test, columns=['color_category'], drop_first=True)


In [9]:
print(X_train)



     firmness  hue  saturation  brightness  sound_db  weight_g  size_cm3  \
132      75.6   84          69          58        69       265       144   
225      53.3  324          59          48        59       208       183   
238      90.5   73          76          66        73       234       125   
119      53.7  318          79          53        59       241       236   
136      20.3   17          54          10        56       219       262   
..        ...  ...         ...         ...       ...       ...       ...   
106      98.8   91          76          59        73       259       138   
14       28.3  307          50          52        45       184       236   
92       69.4   58          79          68        69       215       192   
179      49.8  303          69          54        63       258       239   
102      44.1  287          64          38        58       194       210   

            ripeness  color_category_dark green  color_category_green  \
132  pre-condi

In [17]:
from sklearn import preprocessing

label_encoder = preprocessing.LabelEncoder()
X_train['ripeness']= label_encoder.fit_transform(X_train['ripeness'])
X_test['ripeness']= label_encoder.fit_transform(X_test['ripeness'])


X_train['ripeness'].unique()

array([3, 0, 2, 1, 4])

In [13]:
print(Y_train)

132    3
225    0
238    2
119    0
136    1
      ..
106    2
14     1
92     3
179    0
102    0
Name: ripness_encoder, Length: 200, dtype: int64


In [15]:
model.fit(X_train,Y_train)

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [18]:
y_pred = model.predict(X_test)
print(y_pred)

[3 0 1 0 3 2 0 2 3 3 3 1 0 0 0 4 4 2 4 4 4 0 1 3 1 4 2 0 0 0 1 1 1 0 4 0 2
 4 4 4 4 4 0 1 4 3 2 1 2 2]


In [22]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
# Accuracy (how many correct)
print("Accuracy:", accuracy_score(Y_test, y_pred))

# Confusion Matrix
print("Confusion Matrix:\n", confusion_matrix(Y_test, y_pred))

# Detailed classification report
print("Classification Report:\n", classification_report(Y_test, y_pred))

Accuracy: 1.0
Confusion Matrix:
 [[13  0  0  0  0]
 [ 0  9  0  0  0]
 [ 0  0  8  0  0]
 [ 0  0  0  7  0]
 [ 0  0  0  0 13]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00         8
           3       1.00      1.00      1.00         7
           4       1.00      1.00      1.00        13

    accuracy                           1.00        50
   macro avg       1.00      1.00      1.00        50
weighted avg       1.00      1.00      1.00        50

